version: "3.3"

services:
  webserver:
    container_name : musique_js
    # Use custom image based on php-apache official image
    build: .
    # Run the services as the same user as the host's one, or as user with uid 1000
    user: "${UID:-1001}:${GID:-1001}"
    # Expose HTTP/S ports
    ports:
      - "8881:80"
    working_dir: /var/www/html # chemin virtuel pointant vers le container déployé
    volumes: 
      # Served files
      - ./www:/var/www/html
    sysctls:
      # Allow OS to bind 80 port to unprivileged (eg. non-root) users
      - net.ipv4.ip_unprivileged_port_start=0 
